In [7]:
import numpy as np

In [11]:
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])

In [13]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [14]:
a[1,2]

11

In [36]:
a.shape
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [16]:
a.ndim

2

In [17]:
a.size

10

In [18]:
a[1,2]

11

In [19]:
a[0:2,0:3]

array([[ 1,  2,  3],
       [ 6,  8, 11]])

In [20]:
a[:3,:2]

array([[1, 2],
       [6, 8]])

In [41]:
mean_a = a.mean(axis=1)

In [42]:
# Ответ на 1 задание
mean_a.shape
mean_a

array([2. , 8.4])

In [47]:
a_centered = np.subtract(a.T,mean_a)

In [48]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [49]:
#Ответ на второе задание
a_centered.shape

(5, 2)

In [50]:
a1=a_centered[:,0]
a1

array([-1.,  0.,  1.,  1., -1.])

In [51]:
a2=a_centered[:,1]
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [52]:
a_centered_sp=np.dot(a1,a2)
a_centered_sp

8.0

In [56]:
N=a.shape[0]
N

2

In [57]:
#Ответ на третье задание
result=a_centered_sp/(N-1) 
result

8.0

In [3]:
#Задание 1
import pandas as pd
authors = pd.DataFrame({'author_id':[1, 2, 3] ,'author_name': ['Тургенев', 'Чехов', 'Островский']},columns=['author_id','author_name'])
authors
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3] ,'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]},columns=['author_id','book_title','price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [4]:
authors_price=pd.merge(authors,books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [7]:
top5=authors_price.sort_values(by='price').tail()
top5

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

In [23]:

df1=authors_price.groupby('author_name').agg({'price':'mean'}).rename(columns={'price':'mean_price'})
df1

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [25]:
df2=authors_price.groupby('author_name').agg({'price':'max'}).rename(columns={'price':'max_price'})
df2

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [26]:
df3=authors_price.groupby('author_name').agg({'price':'min'}).rename(columns={'price':'min_price'})
df3

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [28]:
authors_stat=pd.concat([df1, df2, df3], axis = 1)

authors_stat

mean_price  max_price  min_price
author_name                                  
Островский   330.000000        370        290
Тургенев     366.666667        450        300
Чехов        475.000000        500        450